### ISSUE TITLE
'fs' package not included as dependency

### ISSUE THREAD

**Issue by michaelimstepf** [miguelmota/ethereum-input-data-decoder#1]
Thanks a lot for this script. I imported it through yarn / webpack in a Rails app but get an error message because `fs` was undefined. Would it make sense to include `fs` as a dependency?

**Comment by miguelmota** [comment]
`fs` is a native module so don't think it should be in `package.json`. This might be an issue with your yarn or webpack configuration.

@michaelimstepf

**Comment by miguelmota** [comment]
You'll need to use browserify to use it on the front end. I've provided an example http://lab.moogs.io/ethereum-input-data-decoder

@michaelimstepf

**Comment by michaelimstepf** [comment]
Ok thanks, I'll check that out
