### ISSUE TITLE
[Request] Allow to pass JSON data directly

### ISSUE THREAD

**Issue by mesqueeb** [miguelmota/ethereum-input-data-decoder#11]
Please allow the package to also accept JSON data directly instead of having to pass a directory path. It's much more flexible to use then imo.

**Comment by miguelmota** [comment]
From README

> Alternatively, you can pass ABI array object to constructor;
> 
> ```js
> const abi = JSON.parse(fs.readFileSync(`${__dirname}/abi.json`));
> const decoder = new InputDataDecoder(abi);
> ```

**Comment by mesqueeb** [comment]
@miguelmota I was confused as you are still reading from a directory path.

Maybe you can change the readme to: `const abi = JSON.parse(jsonObject)` I think it would be more clear. What do you think? : )

**Comment by miguelmota** [comment]
@mesqueeb good suggestion!
