### ISSUE TITLE
How to decode <BN: xxxx> to a normal integer?

### ISSUE THREAD

**Issue by mesqueeb** [miguelmota/ethereum-input-data-decoder#12]
Is there an option to get integers instead of big numbers? I'm having trouble analysing big numbers.

Cheers!

**Comment by miguelmota** [comment]
```js
var BN = require("bn.js")

var n = new BN("55")

console.log(n.toString(10)) // "5"
console.log(n.toNumber()) // 55
```

Please keep in mind that JavaScript only supports numbers up to 64 bits. Solidity numbers can be up to 256 bits, so you run the risk of truncation when casting or having the big number library error out

```js
var n = new BN("543534254523452352345234523455")

console.log(n.toString(10)) // "543534254523452352345234523455"
console.log(n.toNumber()) // ERROR!
```
