### ISSUE TITLE
Implement support for ABIEncoderV2

### ISSUE THREAD

**Issue by hcaw** [miguelmota/ethereum-input-data-decoder#15]
In its current state the this decoder will not work with ABIEncoderV2. I suggest it be upgraded to also support the new ABI types allowed under this (currently experimental) feature.
However, due to arbitrary levels of nesting of dynamic types allowed under ABIEncoderV2, it would probably make more sense to change the data structure of the output from the decoder so it's easier to work out the name, type and value of each parameter.
For instance of the following function is defined in Solidity.
```solidity
struct User {
    uint256 id;
    string name;
    address userAddr;
    Token[] tokensOwned;
}
struct Token {
    address tokenAddress;
    uint256 tokensOwned;
}
function addUser(User user) { ... }
```
The output could use a recursively structured object, such as:
```json
{
  "inputs": [
    {
      "name": "user",
      "type": "tuple",
      "value": [
        {
          "name": "id",
          "type": "uint256",
          "value": "424242"
        },
        {
          "name": "name",
          "type": "string",
          "value": "Ford Prefect"
        },
        {
          "name": "userAddr",
          "type": "address",
          "value": "0x863DF6BFa4469f3ead0bE8f9F2AAE51c91A907b4"
        },
        {
          "name": "tokensOwned",
          "type": "tuple[]",
          "value": [
            {
              "type": "tuple",
              "value": [
                {
                  "name": "tokenAddress",
                  "type": "address",
                  "value": "0x0D8775F648430679A709E98d2b0Cb6250d2887EF"
                },
                {
                  "name": "tokensOwned",
                  "type": "uint256",
                  "value": "100"
                }
              ]
            },
            {
              "type": "tuple",
              "value": [
                {
                  "name": "tokenAddress",
                  "type": "address",
                  "value": "0x10B0882603c24AF9f1c07cde9f5a06B1300A8c00"
                },
                {
                  "name": "tokensOwned",
                  "type": "uint256",
                  "value": "123123123"
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "name": "addUser"
}
```

**Comment by hcaw** [comment]
I'll make a start on implementing this :+1:

**Comment by miguelmota** [comment]
@hcaw sorry for the delay. The output structure looks good 👍

**Comment by miguelmota** [comment]
There's an [ABIEncoderV2 branch](https://github.com/miguelmota/ethereum-input-data-decoder/tree/ABIEncoderV2) (WIP)

**Comment by liamaharon** [comment]
Hi @hcaw @miguelmota, I'm encountering what I think may be unexpected behaviour when decoding inputs with a `tuple[]` type. I think it may be related to the implementation referenced in this issue.

See https://github.com/miguelmota/ethereum-input-data-decoder/issues/19
Code example with more information: https://github.com/liamaharon/decode-tuple-arr-example

Appreciate any help deciphering if this is an issue with ethereum-input-data-decoder or me misinterpreting the data it's returning to me. Thanks.
