### ISSUE TITLE
Decoded int exceeds width: 160 vs 256 on tranfersFrom() ERC721 contract

### ISSUE THREAD

**Issue by jamesmorgan** [miguelmota/ethereum-input-data-decoder#16]
Hi, I have been using this library successfully and its works great but have hit a small problem when trying to decode a transactions on live. 

This transaction in question is this: https://etherscan.io/tx/0x94fadf5f5c7805b8ceb8a13a0a7fbce06054ff08cdfdc2fd555a7902592aebe6

Interestingly enough etherscan also fails to decode the inputs and you can see the error in the browser console.

I actually noticed this in a backend service which we use this library to decode txs for specific addresses.

The error is `Decoded int exceeds width: 160 vs 256`

I guess the reason is that the data provided to args two `_address` is of the wrong type/length. 

Got any ideas on how to check for this and order handle it?

Any help would be appreciated.

Thanks

James

**Comment by miguelmota** [comment]
hey @jamesmorgan, the issue is now fixed in the latest release. Thanks for reporting the bug
