### ISSUE TITLE
SyntaxError: Unexpected token else

### ISSUE THREAD

**Issue by zzr2zr** [miguelmota/ethereum-input-data-decoder#17]
The following error occurred when I decoded：

`root@kali:~/node-v4.9.1-linux-x64/bin# ./ethereum_input_data_decoder --abi DaysBank.abi --input data.txt 
/root/node-v4.9.1-linux-x64/lib/node_modules/ethereum-input-data-decoder/cli.js:55
} else {
  ^^^^

SyntaxError: Unexpected token else
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
`
This is my file and data. What is wrong with it?
`[{"constant":false,"inputs":[{"name":"b64email","type":"string"}],"name":"payforflag","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"gift","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"flagnum","type":"uint256"},{"indexed":false,"name":"b64email","type":"string"}],"name":"SendFlag","type":"event"}]`

`0x608060405234801561001057600080fd5b5060028054600160a060020a03191633179055610455806100326000396000f3006080604052600436106100825763ffffffff7c0100000000000000000000000000000000000000000000000000000000600035041663652e9d91811461008757806366d16cc31461009e5780636bc344bc146100b357806370a082311461010c5780637ce7c9901461014c578063a9059cbb1461017d578063cbfc4bce146101ae575b600080fd5b34801561009357600080fd5b5061009c6101dc565b005b3480156100aa57600080fd5b5061009c61021a565b3480156100bf57600080fd5b506040805160206004803580820135601f810184900484028501840190955284845261009c9436949293602493928401919081908401838280828437509497506102789650505050505050565b34801561011857600080fd5b5061013a73ffffffffffffffffffffffffffffffffffffffff6004351661033b565b60408051918252519081900360200190f35b34801561015857600080fd5b5061009c73ffffffffffffffffffffffffffffffffffffffff6004351660243561034d565b34801561018957600080fd5b5061009c73ffffffffffffffffffffffffffffffffffffffff600435166024356103d2565b3480156101ba57600080fd5b5061013a73ffffffffffffffffffffffffffffffffffffffff60043516610417565b33600090815260016020526040902054156101f657600080fd5b33600090815260208181526040808320805460019081019091559182905290912055565b3360009081526020819052604090205460011461023657600080fd5b336000908152600160208190526040909120541461025357600080fd5b3360009081526020818152604080832080546001908101909155909152902060029055565b33600090815260208190526040902054612710111561029657600080fd5b7fb1bc9a9c599feac73a94c3ba415fa0b75cbe44496bfda818a9b4a689efb7adba6001826040518083815260200180602001828103825283818151815260200191508051906020019080838360005b838110156102fd5781810151838201526020016102e5565b50505050905090810190601f16801561032a5780820380516001836020036101000a031916815260200191505b50935050505060405180910390a150565b60006020819052908152604090205481565b6002811161035a57600080fd5b3360009081526020819052604090205460021061037657600080fd5b336000908152602081905260408120548290031161039357600080fd5b336000908152602081905260408082208054849003905573ffffffffffffffffffffffffffffffffffffffff9390931681529190912080549091019055565b600181116103df57600080fd5b336000908152602081905260409020546001106103fb57600080fd5b3360009081526020819052604090205481111561039357600080fd5b600160205260009081526040902054815600a165627a7a7230582031248cecd3490d708a53c37a5b45e0b4401ff31020534cf7b2879aacf8ca10560029`

**Comment by miguelmota** [comment]
@zzr2zr thanks for reporting. There was a bug. It's fixed now in the latest release.
