### ISSUE TITLE
decode contract input data

### ISSUE THREAD

**Issue by thbach** [miguelmota/ethereum-input-data-decoder#31]
Hi, how would i decode the input data for a contract creation. Since the ABI isnt known unless I am the contract creator or know the contract address

**Comment by grimreaper619** [comment]
+1 How do I decode constructor parameters used while deploying contract

**Comment by miguelmota** [comment]
The ABI must be known in order to determine the solidity types which are required for the decoder to know the input parameter offsets, otherwise it's not really possible without the ABI.
