### ISSUE TITLE
decoding not working correctly when functions have arrays as parameters

### ISSUE THREAD

**Issue by niccolopetti** [miguelmota/ethereum-input-data-decoder#35]
this is an example to reproduce this issue:

```
pragma solidity >=0.8.0 <0.9.0;
contract Example  {
    
    function foo(string[2] calldata a, uint[2] calldata b) external returns (address) {
        return msg.sender;
    }
}
```
if you compile this Smart Contract, deploy it to a network and call the foo function, then pasting the abi and the transaction's input data in https://lab.miguelmota.com/ethereum-input-data-decoder/example/
will produce unexpected results,
as shown in the image
![image](https://user-images.githubusercontent.com/22686876/115161146-42251180-a09c-11eb-9005-a3f7a53ffaa6.png)

if it may be helpful the input data I passed to the transaction were:
```
a: [  "92bf076a-2b42-4df3-a74b-ee9f457225b8","7ee5645d-bd02-4526-ab69-039a1a54731f"]
b: [   "9",   "70" ]
```

**Comment by miguelmota** [comment]
@niccolopetti 

Related https://github.com/miguelmota/ethereum-input-data-decoder/issues/28#issuecomment-819119220
