### ISSUE TITLE
Type 'typeof import(".../node_modules/ethereum-input-data-decoder/index")' has no construct signatures.

### ISSUE THREAD

**Issue by dblock** [miguelmota/ethereum-input-data-decoder#40]
0.3.5 release [broke](https://github.com/dblock/lost-robbies/runs/3609473067?check_suite_focus=true
) something

```
Error: src/update.ts(55,30): error TS2351: This expression is not constructable.
  Type 'typeof import("/home/runner/work/lost-robbies/lost-robbies/node_modules/ethereum-input-data-decoder/index")' has no construct signatures.
Error: src/update.ts(93,30): error TS2351: This expression is not constructable.
  Type 'typeof import("/home/runner/work/lost-robbies/lost-robbies/node_modules/ethereum-input-data-decoder/index")' has no construct signatures.
Error: src/update.ts(178,34): error TS2351: This expression is not constructable.
  Type 'typeof import("/home/runner/work/lost-robbies/lost-robbies/node_modules/ethereum-input-data-decoder/index")' has no construct signatures.
```

```typescript
var inputDataDecoder = new InputDataDecoder(await getAbi());
```

Not sure what the issue is, didn't debug. Probably https://github.com/miguelmota/ethereum-input-data-decoder/commit/eb5bc44ac59f536d8801e26aac77489c85b451e2. Locking back at 0.3.4 [works](https://github.com/dblock/lost-robbies/runs/3609500982?check_suite_focus=true).

To repro, check out https://github.com/dblock/lost-robbies, bump version in package.json, `npm install` and `npm run sales`.

**Comment by miguelmota** [comment]
Closing since it's working with latest version
