### ISSUE TITLE
[Fix] Typescript run problem

### ISSUE THREAD

**Issue by quocanhvmo** [miguelmota/ethereum-input-data-decoder#45]
- If you get problem with constructor when build and run
[**This way is how I solve the problem when try to run ethereum-input-data-decoder on typescript source code**](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by hoangnh2912** [comment]
Very helpful  😘😘😘😘😘😘

**Comment by hoangnh2912** [comment]
nice fix
