### ISSUE TITLE
smart contract creation input data not working

### ISSUE THREAD

**Issue by maxd001** [miguelmota/ethereum-input-data-decoder#5]
Hi, I am trying to decode a simplestorage contract i've deployed, but getting back blank when trying to decode the data string.

my smart contract

```
pragma solidity ^0.4.18;

contract simplestorage { 
    uint public storedData; 
    
    function simplestorage(uint initVal) public { 
        storedData = initVal; 
    } 
    
    function set(uint x) public { 
        storedData = x; 
    } 
    
    function get() public constant returns (uint retVal) { 
        return storedData; 
    } 
}
```

ABI (in abi.json file)
`[{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"initVal","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"}]`

DATA:

"0x6060604052341561000f57600080fd5b60405160208061014b833981016040528080519060200190919050508060008190555050610109806100426000396000f3006060604052600436106053576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632a1afcd914605857806360fe47b114607e5780636d4ce63c14609e575b600080fd5b3415606257600080fd5b606860c4565b6040518082815260200191505060405180910390f35b3415608857600080fd5b609c600480803590602001909190505060ca565b005b341560a857600080fd5b60ae60d4565b6040518082815260200191505060405180910390f35b60005481565b8060008190555050565b600080549050905600a165627a7a72305820533b4b05fd6a7ab04f015270e7710e56bab06315aafb2a8bd0f01789dc1290b30029000000000000000000000000000000000000000000000000000000000000022c"

commands executed:

d = new InputDataDecoder('/<somepath>/abi.json');
data="DATAFROMABOVE";
res = d.decodeData(data);
{}   <-- THIS IS MY OUTPUT

What am i doing wrong here?

**Comment by kolya182** [comment]
@maxd001 Try `('./abi.json')`

**Comment by miguelmota** [comment]
Unfortunately I don't have a solution for decoding contract creation input data. 
If someone knows a good way of achieving then we'd love to know about it.
Happy to merge in any PRs.

**Comment by miguelmota** [comment]
Latest release can decode contract creation input data

**Comment by pranavburnwal** [comment]
> Latest release can decode contract creation input data

@miguelmota 
I am not able to work out the contract creation input decoder.
Can you please give a brief help on that?

Thanks!
