### ISSUE TITLE
Failed to minify

### ISSUE THREAD

**Issue by TiagoGouvea** [miguelmota/ethereum-input-data-decoder#6]
I'm having that problem when trying to build my react app:

```
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/ethereum-input-data-decoder/index.js:5 

Read more here: http://bit.ly/2tRViJ9
```

The link says: "Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years."

It's a good idea, to build the the code to ES5 too before publish.

**Comment by miguelmota** [comment]
@TiagoGouvea shoud work now, try updating to the latest version

```bash
npm i ethereum-input-data-decoder@latest
```

Thanks for reporting!
