### ISSUE TITLE
Error happens when constructor doesn't have "string" type input

### ISSUE THREAD

**Issue by seohoryu** [miguelmota/ethereum-input-data-decoder#7]
Hi. Thank you for providing this useful library. 
Unfortunately, I've noticed there was a small problem.

If a constructor doesn't have a string type input parameter, it affects decoding other parameters in functions. I used your given example and just changed constructor part as follow.

* ABI
...
  {
    "inputs": [
      { "name": "_masterAuth", "type": "address" },
      { "name": "_name", "type": "uint256"} // changed from "string" to "uint256"
    ],
    "payable": false,
    "type": "constroctor"
  },
...

* Decoding Result after ABI change
{
  "types": [
    "address",
    "uint256"
  ],
  "inputs": [
    "0x00000000000000000000000000000000000000a0",
    {
      "_bn": "f3df64775a2dfb6bc9e09dced96d0816ff5055bf95da13ce5b6c3f53b97071c8"
    }
  ]
} 

* Expected Result
{
  "name": "registerOffChainDonation",
  "types": [
    "address",
    "uint256",
    "uint256",
    "string",
    "bytes32"
  ],
...

I think this happens at line 49 "ethers.Interface.decodeParams(types, data)" in https://github.com/miguelmota/ethereum-input-data-decoder/blob/master/index.js
I wrapped this part with try-catch, it seems to work well but I don't convince this is a right way to avoid the error.
Could you please take a look?
Thanks,

**Comment by miguelmota** [comment]
@seohoryu Thank you for reporting! will take a look. In your example, is `constroctor` on purpose or a typo?

**Comment by miguelmota** [comment]
@seohoryu recently pushed an update; install the latest version to get the fix

```bash
npm i ethereum-input-data-decoder@latest
```

Please reopen this issue if still experiencing problems

**Comment by seohoryu** [comment]
Great! Thank you for the fix. 👍 It works well on my test env.
