### ISSUE TITLE
ethereumjs-abi bug: "Decoded int exceeds width: 160 vs 256 "

### ISSUE THREAD

**Issue by kelvinkuo** [miguelmota/ethereum-input-data-decoder#8]
I scanned the ethereum main chain, tx_hash = 0x0fc8f1cb5112c4679dfcbde54306cabecedfbfd115030252b2e3d77ed7b7da8c.
decode the input and there is a error msg "Decoded int exceeds width: 160 vs 256 "

const ether_decoder = require('ethereum-input-data-decoder');
const decoder = new ether_decoder(config.get('ERC20-abi'));
//...
const callObj = decoder.decodeData(transaction.input);
//...

ethereum-input-data-decoder version 0.0.6

**Comment by miguelmota** [comment]
@kelvinkuo that's interesting. In solidity the `address` type is the same as a `uint160`, but the input for that transactions has an address of `uint256` which I've never seen before. 

Submitted an issue to ethereumjs-abi since that's the library it's using for decoding solidity types

https://github.com/ethereumjs/ethereumjs-abi/issues/66

**Comment by miguelmota** [comment]
@kelvinkuo I pushed an update to workaround this issue. Install the latest and you should be good

```
npm i ethereum-input-data-decoder@latest
```

Working example using your tx data

 ```js 
const data = '0xa9059cbb85f1150654584d0192059454e9dc1532d9d9cf914926406a02370cea80cf32f600000000000000000000000000000000000000000000000000000000033dc10b'

const result = decoder.decodeData(data)
console.log(result.inputs[0].toString(16)) // e9dc1532d9d9cf914926406a02370cea80cf32f6
console.log(result.inputs[1].toString(10)) // 54378763
```

**Comment by miguelmota** [comment]
@kelvinkuo please reopen issue if you still have problems

**Comment by kelvinkuo** [comment]
thanks @miguelmota

**Comment by maulikvora** [comment]
@miguelmota I have installed latest version.
But I still get this error. for same methodId - `transfer` - a9059cbb

I tried with my abi and input data at https://lab.miguelmota.com/ethereum-input-data-decoder/example/, its working good.
Do you see any reason why it won't work on my server.
I compared files too, all your changes to fix this are there.
for eg.
`if (methodId === 'a9059cbb') {
+          inputsBuf = Buffer.concat([new Buffer(12), inputsBuf.slice(12,32), inputsBuf.slice(32)])
+        }`

**Comment by maulikvora** [comment]
@miguelmota Surprising for me commenting out this code worked.
What do you suggest to make this working for all contracts? without changing your code.

**Comment by maulikvora** [comment]
@miguelmota 
I further debugged out, if I comment out this line, its working. `inputsBuf = Buffer.concat([new Buffer(12), inputsBuf.slice(12,32), inputsBuf.slice(32)])`

is there something different in my contract?
https://rinkeby.etherscan.io/tx/0x886bd8134098831dfcb7e51969233d59f061a201e1c071dd5952e28f6df316e9

Should we add there some more condition like if method is **transfer** and **toAddress** doesn't have 12bytes prefix, then only we apply this line? `inputsBuf = Buffer.concat([new Buffer(12), inputsBuf.slice(12,32), inputsBuf.slice(32)])`

Your help is appreciated.
